


library(tidyverse)
library(lubridate)
library(Cairo)
library(ggthemes)
library(png)
library(cowplot)


library(extrafont)

# SET ---------------------------------------------------------------------





minesweeper_font = "MINE-SWEEPER"

title_font <- "#707ca4"
subtitle_font <- "#8f99b7"
axis_font <- "#707ca4"
bbbv_font <- "#abb3c9"

bbbv_text <- 
  
  "Boards of identical size can present varying levels 
of difficulty in Minesweeper. The Bechtel's Board 
Benchmark Value (3BV) seeks to estimate this 
difficulty by counting the minimum number of 
left-clicks required on the mouse to clean the board"


smiley <- readPNG("minesweeper_smiley.png")

dat <- read_csv(here::here("raw_data", "stats_csv.csv")) |> 
  unite("timestamp", Day:Sec, sep = "_", remove = F) |> 
  mutate(timestamp = dmy_hms(timestamp),
         idx = row_number(), 
         time_since_last = as.numeric(timestamp - lag(timestamp)))

int <- dat |> filter(mode == "INT")

int <- int |> 
  mutate(date = as.Date(timestamp))






CairoWin()
int |> 
  ggplot(aes(date, Time)) + 
  geom_point(aes(y = Time, color = BBBV), shape = "-",   size = 10,  alpha = 1) + 
  geom_line(stat = "smooth", color = "steelblue", size = 0.8) + 
  geom_line(stat = "summary", size = 0.9, color = "white") +
  
  theme_tufte() + 
  
  labs (title = "I've been self-tracking my performance in Minesweeper for the past few months", 
        subtitle = "Each short dash represents a completed game of Minesweeper on the intermediate difficulty board",
        y = "Seconds to complete", 
        color = "3BV", 
        caption = "Data has been autogenerated using Minesweeper Arbiter. Visualization by Martín Pons | @MartinPonsM") + 
  
  guides(col = guide_colourbar(title.position = "top", 
                               direction = "horizontal", 
                               label = TRUE,
                               title = "3BV",
                               title.theme = element_text(family = minesweeper_font,
                                                          color = "white", 
                                                          hjust = 0.5, 
                                                          size = 9),
                               label.theme = element_text(color = "white", 
                                                          family = minesweeper_font, 
                                                          size = 7),
                               barwidth = 14.8),
         fill = guide_colourbar(direction = "horizontal")) +
  
  
  geom_text(aes(x = ymd(20240127),
                # xend = ymd(20240206),
                y = 100, 
                label = bbbv_text),
            hjust = "left",
            vjust = "top", 
            color = bbbv_font, 
            lineheight = 1.5, 
            family = "Segoe UI Light", 
            size = 4.6) +
  
  scale_color_continuous(type = "viridis")  + 
  
  theme(#panel.background = element_rect(fill = "black"), 
    plot.background = element_rect(fill = "black"),
    legend.position = c(0.85, 0.93),
    legend.text = element_text(color = "white"),
    plot.title = element_text(family = "MINE-SWEEPER", color = title_font, size = 15, hjust = 0.132), 
    plot.subtitle = element_text(family = "Tahoma", color = subtitle_font, size = 18, hjust = 0),
    plot.caption = element_text(family = "Tahoma", color = bbbv_font, size = 14),
    axis.text = element_text(family = "MINE-SWEEPER", color = axis_font), 
    axis.title.y = element_text(color = subtitle_font, family = "Tahoma", size = 17),
    axis.line = element_line(color = "white")) 



# ggdraw() + draw_plot(minesweeper_plot) +  draw_image(smiley, width = 0.9, height = 0.05, scale = 0.5)
