# This script creates a visualization of a self-tracking performance in the game minesweeper using
# The minesweeper clone, "Arbiter", which registers all kinds of useful statistics of all completed 
# games. You can download arbiter through this link. https://minesweepergame.com/download/arbiter.php
# it requires no installation

# The visualization includes a font family themed in the shape of the minesweeper numbers and is not
# a default font in Windows. You can download it here
# https://fontstruct.com/fontstructions/show/1501665/mine-sweeper





# SET ---------------------------------------------------------------------

# load libreries
library(tidyverse)
library(lubridate)
library(Cairo)
library(ggthemes)
library(extrafont)


# viz. constants
minesweeper_font <- "MINE-SWEEPER"

title_color <- "#707ca4"
subtitle_color <- "#8f99b7"
bbbv_text_color <- "#abb3c9"
axis_line_color <- "#3c445d"

bbbv_text_family <- "Segoe UI Light"
  
bbbv_text <- 
  "Boards of identical size can present varying levels 
of difficulty in Minesweeper. The Bechtel's Board 
Benchmark Value (3BV) seeks to estimate this 
difficulty by counting the minimum number of 
left-clicks required on the mouse to clean the board"



# DATA WRANGLING ----------------------------------------------------------


int <- read_csv(here::here("raw_data", "stats_csv.csv")) |> # load
  filter(mode == "INT") |> # getting intermediate boards
  
      # format date
      unite("date", Day:Year, sep = "_", remove = F) |> 
      mutate(date = dmy(date))




# VISUALIZATION -----------------------------------------------------------



CairoWin() # Adjust height and width arguments to get a better fit
int |> 
  ggplot(aes(date, Time)) + 
  geom_point(aes(y = Time, color = BBBV), shape = "-",   size = 10,  alpha = 1) + 
  geom_line(stat = "smooth", color = "steelblue", size = 0.8) + 
  geom_line(stat = "summary", size = 0.9, color = "white") +
  
  theme_tufte() + 
  
  labs (title = "I've been self-tracking my performance in Minesweeper for the past few months", 
        subtitle = "Each short dash represents a completed game of Minesweeper on the intermediate difficulty board",
        y = "Seconds to complete", 
        color = "3BV", 
        caption = "Data has been autogenerated using Minesweeper Arbiter. Visualization by Martín Pons | @MartinPonsM") + 
  
  guides(col = guide_colourbar(title.position = "top", 
                               direction = "horizontal", 
                               label = TRUE,
                               title = "3BV",
                               title.theme = element_text(family = minesweeper_font,
                                                          color = "white", 
                                                          hjust = 0.5, 
                                                          size = 9),
                               label.theme = element_text(color = "white", 
                                                          family = minesweeper_font, 
                                                          size = 7),
                               barwidth = 14.8),
         fill = guide_colourbar(direction = "horizontal")) +
  
  
  geom_text(aes(x = ymd(20240127),
                # xend = ymd(20240206),
                y = 100, 
                label = bbbv_text),
            hjust = "left",
            vjust = "top", 
            color = bbbv_text_color, 
            lineheight = 1.5, 
            family = bbbv_text_family, 
            size = 4.6) +
  
  scale_color_continuous(type = "viridis")  + 
  
  theme(#panel.background = element_rect(fill = "black"), 
    plot.background = element_rect(fill = "black"),
    legend.position = c(0.85, 0.93),
    legend.text = element_text(color = "white"),
    plot.title = element_text(family = "MINE-SWEEPER", color = title_color, size = 15, hjust = 0.132), 
    plot.subtitle = element_text(family = "Tahoma", color = subtitle_color, size = 18, hjust = 0),
    plot.caption = element_text(family = "Tahoma", color = bbbv_text_color, size = 14),
    axis.text = element_text(family = "MINE-SWEEPER", color = axis_font), 
    axis.title.y = element_text(color = subtitle_color, family = "Tahoma", size = 17),
    axis.line = element_line(color = axis_line_color)) 

